uploads = []
outputs = []

[[generated]]
id = "NHoPqZxezYYhZYNd_W0_5"
uri = "file://artifacts/nexus/public/hero-orbital.png"
type = "image"
title = "Orbital compute infrastructure"

[[generated]]
id = "nhmuU1NEEkK53Z7IiBqdl"
uri = "file://artifacts/nexus/public/neural-mesh.png"
type = "image"
title = "Neural mesh network"

[[generated]]
id = "zThEN47VT3hVWUXKWOjbQ"
uri = "file://artifacts/nexus/public/machine-core.png"
type = "image"
title = "Autonomous machine core"
